config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: "home#index"

  get 'pages/terms' => 'pages#terms'

  get 'pages/about' => 'pages#about'

  get 'home/index'

  get 'contacts' => 'contacts#new'

  resources :articles do
     resources :comments 
  end  
  resource :contacts, only: [:new,:create]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @articles = Article.all 
  end

  def show
    @article = Article.find(params[:id])
  end


 def create
    @article = Article.new(article_params)
  if  @article.valid?
    @article.save
    redirect_to @article
  else
  render action: 'new'
  end  
 end

 def edit
  @article = Article.find(params[:id])   
 end
def update
   @article = Article.find(params[:id]) 
   if @article.update(article_params)
    redirect_to @article
   else
    render action:'edit'
   end 
end
  def destroy
    @article = Article.find(params[:id]) 
    @article.destroy

    redirect_to articles_path
  end

private
  def article_params
    params.require(:article).permit(:title,:text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:author,:body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new    
  end
  def create    
  @contact = Contact.new(contact_params)
  if  @contact.valid?
    @contact.save
  else
  render action: 'new'
  end  
 end

private
  def contact_params
    params.require(:contact).permit(:email,:message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/create.html.erb
<h1>Thank you! </h1>
<p>Article has been created!</p>
<%= link_to 'Show all articles',articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article:</h1>

<%= form_for :article, url: article_path(@article),method: :put   do |f| %>
	<p>
		<%=f.label :title %>
		<%=f.text_field :title %>
	</p>
	<p>
		<%=f.label :text %>
		<%=f.text_field :text %>
	</p>
	<p>
		<%=f.submit %>
	</p>
<% end %>

app/views/articles/index.html.erb
<h1>List of articles:</h1>

<%= @articles.each do |article| %> 
	<h2>
	<%= article.title %> 	
	</h2>
<p>
	<%= article.text %>		
</p>
<p>
	<%= link_to 'Show',article_path(article) %> |
	<%= link_to 'Edit',edit_article_path(article) %> |
	<%= link_to 'Destroy',article_path(article), method: :delete, data: { confirm: 'Are you sure?'} %>
</p>
<hr/>
<% end %> 

app/views/articles/new.html.erb
<h1>Article</h1>
<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%=f.label :title %>
		<%=f.text_field :title %>
	</p>
	<p>
		<%=f.label :text %>
		<%=f.text_field :text %>
	</p>
	<p>
		<%=f.submit %>
	</p>



<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %> </h1>
<p>
	 <%= @article.text %> 
 </p> 

<h2>Comments</h2>
	<% @article.comments.each do |comment| %>
		<p>
		<i><%= comment.author %> said:</i><br/>
		<%= comment.body %>
		</p>
	<% end %>
<h2>Add comments</h2>

<%= form_for([@article, @article.comments.build]) do |f|%> 
	<p>
		<%=f.label :author %>
		<%=f.text_field :author %>
	</p>
	<p>
		<%=f.label :body %>
		<%=f.text_field :body %>
	</p>
	<p>
		<%=f.submit %>
	</p>
<% end %>

app/views/contacts/create.html.erb
<p>Thanks!</p>

app/views/contacts/new.html.erb
<h1>Contact us</h1>
<%= form_for :contact, url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %>
	<p>
	    <ul>
		<%= @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		<ul>

	</p>
	<% end %>
	<p>
		<%=f.label :email %>
		<%=f.text_field :email %>
	</p>
	<p>
		<%=f.label :message %>
		<%=f.text_field :message %>
	</p>
	<p>
		<%=f.submit 'Send message' %>
	</p>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	 <p class="notice"><%= notice %></p>
	 <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About us </h1>
<p>
	Lorem Lorem Lorem Lorem Lorem Lorem 
</p>

app/views/pages/terms.html.erb
<h1>Terms  of Service </h1>
<p>
	Lorem 12345678910
</p>